#!/bin/bash

# What modules, in what order
MODULES="todo daypercentage cputemp volume ram networkdowntraffic battery date time"

# Modules that require an active internet connection
ONLINE_MODULES=""

# Delay between showing the status bar
DELAY="1"

# Where the custom modules are stored
CUSTOM_DIR="/home/$USER/.config/dwmbar/modules/custom/"

# Separator between modules
SEPARATOR=" | "

# Padding at the end and beggining of the status bar
RIGHT_PADDING=""
LEFT_PADDING=""
